[package]
name = "multiservice-discovery-shared"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
service-discovery = { path = "../service-discovery" }
serde = { workspace = true }
serde_json = { workspace = true }
ic-types = { workspace = true }
erased-serde = { workspace = true }
regex = { workspace = true }
