[package]
name = "ic-canisters"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
byteorder = "1.5.0"
backoff = { workspace = true }
candid = { workspace = true }
hex = { workspace = true }
ic-agent = { workspace = true }
ic-base-types = { workspace = true }
ic-management-canister-types-private = { workspace = true }
ic-nns-common = { workspace = true }
ic-nns-constants = { workspace = true }
ic-nns-governance = { workspace = true }
ic-nns-governance-api = { workspace = true }
ic-protobuf = { workspace = true }
ic-registry-transport = { workspace = true }
ic-utils = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
cryptoki = { workspace = true }
sha2 = { workspace = true }
simple_asn1 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
ic-sns-wasm = { workspace = true }
trustworthy-node-metrics-types = { workspace = true }
ic-transport-types = { workspace = true }
ic-registry-keys.workspace = true
ic-types.workspace = true
ic-interfaces-registry.workspace = true
ic-registry-nns-data-provider.workspace = true
ic-registry-canister-api = { workspace = true }
icrc-ledger-types.workspace = true
ic-node-rewards-canister-api = { workspace = true }
rewards-calculation = { workspace = true }
